"""empty message

Revision ID: 2f88a1359600
Revises: 
Create Date: 2024-05-13 16:27:25.685063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f88a1359600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_column('following')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
