"""added a about me under USER for profile creativity

Revision ID: fe89d63850d6
Revises: 2f88a1359600
Create Date: 2024-05-13 17:12:28.405621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe89d63850d6'
down_revision = '2f88a1359600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
